Mission_Book/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('login.urls')),
    path('checklist',include('checklist.urls')),
]

checklist/urls.py
from django.urls import path
from . import views
from Mission_Book import settings
from django.conf.urls.static import static

app_name = 'checklist'

urlpatterns = [
    path('',views.index_null, name='index_null'),
    path('index/<int:category>',views.index, name='index'),
    path('missionDetail/<int:mission_id>',views.mission_modal, name='mission_modal')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/urls.py
from django.urls import path
from . import views
from Mission_Book import settings
from django.conf.urls.static import static

app_name='login'

urlpatterns = [
    path('join/', views.join, name='join'),
    path('prolog/<int:num>',views.prolog, name='prolog'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.logout_member, name='logout'),
    path('profile/',views.profile, name='profile'),
    path('mypage/',views.mypage, name='mypage'),
    path('setup/',views.setup, name='setup'),
    path('select_title/',views.select_title, name='select_title'),
    path('change_title/<int:title>/',views.change_title, name='change_title'),
    path('change_title_color/<int:color>/',views.change_title_color, name='change_title_color'),
    path('ending/<int:num>',views.ending, name='ending'),
    path('',views.join, name='join')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

checklist/models.py
from django.db import models

# Create your models here.
class Checklist(models.Model):
    title = models.CharField(max_length=50) #체크리스트 제목
    category = models.IntegerField(default=0) #체크리스트 분류 1=학업 2=친목 3=경험
    is_complete_num = models.BooleanField(default=False) #complete_num의 유효여부
    complete_num = models.IntegerField(default=0) #완료에 필요한 개수
    class_reward = models.FloatField(default=0) #성공시 증가하는 학업스탯
    social_reward = models.FloatField(default=0) #성공시 증가하는 사교스탯
    exp_reward = models.FloatField(default=0) #성공시 증가하는 경험스탯
    total_exp_reward = models.FloatField(default=0) #성공시 증가하는 경험치
    level = models.IntegerField(default=1) #난이도
    content = models.CharField(max_length=100) #체크리스트 내용
    need_class_stat = models.FloatField(default=0) #미션 개방 학업스탯
    need_social_stat = models.FloatField(default=0) #미션 개방 사교스탯
    need_exp_stat = models.FloatField(default=0) #미션 개방 경험스탯
    
    def __str__(self):
        return f'<{self.category}>{self.title}'
    
class MemberChecklist(models.Model):
    member = models.CharField(max_length=20)
    checklist = models.ForeignKey(Checklist, on_delete=models.CASCADE, related_name="MemberChecklist")
    status = models.IntegerField(default=-1)    

checklist/views.py
import datetime

from django.shortcuts import render, redirect, get_object_or_404

from checklist.models import MemberChecklist
from login.views import this_year
from member.models import Member


# Create your views here.

def index_null(request):
    return index(request,1)


def index(request, category):
    user_id = None
    if request.user.is_authenticated:
        user_id = request.user.user_id  # 혹은 request.user.username 등 로그인한 유저의 정보를 사용

    if user_id and datetime.datetime.now().year != this_year:
        return redirect('login:ending',1)

    checklists = MemberChecklist.objects.filter(member=user_id)
    if category == 1:
        some_missionlist_pro = checklists.filter(checklist__category=1, status=0,
                                                 checklist__need_class_stat__lte=request.user.int_stat)  # 카테고리가 1, status가 0인 미션 리스트를 가져옴
        some_missionlist_pre = checklists.filter(checklist__category=1, status=-1,
                                                 checklist__need_class_stat__lte=request.user.int_stat)  # 카테고리가 1, status가 -1인 미션 리스트를 가져옴
        # some_missionlist_pro.order_by('checklist__level')
        # some_missionlist_pre.order_by('checklist__level')
        category_name = '학업'
    elif category == 2:
        some_missionlist_pro = checklists.filter(checklist__category=2, status=0,
                                                 checklist__need_social_stat__lte=request.user.social_stat)  # 카테고리가 2, status가 0인 미션 리스트를 가져옴
        some_missionlist_pre = checklists.filter(checklist__category=2, status=-1,
                                                 checklist__need_social_stat__lte=request.user.social_stat)  # 카테고리가 2, status가 -1인 미션 리스트를 가져옴
        # some_missionlist_pro.order_by('checklist__level')
        # some_missionlist_pre.order_by('checklist__level')
        category_name = '사교'
    elif category == 3:
        some_missionlist_pro = checklists.filter(checklist__category=3, status=0,
                                                 checklist__need_exp_stat__lte=request.user.exp_stat)  # 카테고리가 3, status가 0인 미션 리스트를 가져옴
        some_missionlist_pre = checklists.filter(checklist__category=3, status=-1,
                                                 checklist__need_exp_stat__lte=request.user.exp_stat)  # 카테고리가 3, status가 -1인 미션 리스트를 가져옴
        some_missionlist_pro.order_by('checklist__level')
        some_missionlist_pre.order_by('checklist__level')
        category_name = '경험'
    else:
        some_missionlist = None
    context = {'some_missionlist_pre': some_missionlist_pre,
               'some_missionlist_pro': some_missionlist_pro, 'category_name': category_name}
    return render(request, 'index.html', context)

def mission_modal(request, mission_id):
    member = Member.objects.get(id=request.user.id)
    member_checklist = MemberChecklist.objects.get(member=member.user_id, checklist_id=mission_id)


    # 추가하기
    if request.method == 'POST' and request.POST.get('checklist_add') == '추가하기':
        member_checklist.status = 0
        member_checklist.save()

    # 포기하기
    if request.method == 'POST' and request.POST.get('give_up') == '포기':
        member_checklist.status = -1
        member_checklist.save()

    # 완료하기
    if request.method == 'POST' and request.POST.get('checklist_complete') == '완료':
        member_checklist.status = 1
        member.int_stat+=member_checklist.checklist.class_reward
        member.social_stat+=member_checklist.checklist.social_reward
        member.exp_stat+=member_checklist.checklist.exp_reward
        member.total_exp+=member_checklist.checklist.total_exp_reward
        member_checklist.save()
        member.save()
        return redirect('checklist:index_null' )

    return render(request, 'mission_modal.html', {'member_checklist':member_checklist})

checklist/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'style_yun.css' %}">
    <title>Mission Book</title>
    <style>
        .missions {
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
}

.mission-box {
  width: 45%;
  margin: 10px;
  background-color: white;
  box-shadow: 2px 2px 5px rgba(0, 0, 0, 0.2);
  border-radius: 5px;
  text-align: center;
  padding: 10px;
  overflow: auto; /* 넘치는 내용 생략 */
    display : inline-block;
    margin-right:0px;
    height: 10em;
    line-height: 130px;
}

.mission-box h3 {
  font-size: 16px;
  margin-bottom: 5px;
  {#overflow: hidden;#}
  {#text-overflow: ellipsis; /* 넘치는 글자 생략 */#}
  {#white-space: nowrap; /* 줄바꿈 방지 */#}
}

.mission-box p {
  font-size: 14px;
  margin-bottom: 10px;
  color: gray;
  {#overflow: hidden;#}
  {#text-overflow: ellipsis; /* 넘치는 글자 생략 */#}
  {#white-space: nowrap; /* 줄바꿈 방지 */#}
}
    </style>
</head>
<body>
<!-- 상단바 (네비게이션) -->
<header>
    <a href="{% url 'checklist:index_null' %}"><img src="{% static 'misson_click.png' %}" alt="미션아이콘" width="25px"
                                                    height="25px"/></a>
    <a href="{% url 'login:mypage' %}"><img src="{% static 'info.png' %}" alt="정보아이콘" width="25px" height="25px"/></a>
    <a href="{% url 'login:setup' %}"><img src="{% static 'setup.png' %}" alt="설정아이콘" width="25px" height="25px"/></a>

</header>

<!--사용자 정보 -->
<section class="hd">
    <div class="container">
        <div>
            <a class="name">{{ user.name }}</a>>
            <a class="level">Lv.{{ user.total_exp|add:0 }}</a>
        </div>
        <div>
            <p class="personal explanation">{% if user.title %}{{ user.title }}{% else %} 칭호없음 {% endif %}</p>
        </div>


    </div>
</section>

<!--미션 탭 -->
<div class="mission-tab">
    <div class="mis-btn">
        <a href="{% url 'checklist:index' 1 %}"><img src="{% static 'study.png' %}" alt="학업아이콘"/></a>
    </div>
    <div class="mis-btn">
        <a href="{% url 'checklist:index' 2 %}"><img src="{% static 'getting.png' %}" alt="사교아이콘"/></a>
    </div>

    <div class="mis-btn">
        <a href="{% url 'checklist:index' 3 %}"><img src="{% static 'experience.png' %}" alt="경험아이콘"/></a>
    </div>
</div>

<div class="missions">
    <p class="msg"><span style:bold;>학업</span>에 관련된 미션을 해결하세요 </p>
    <div class="mission-container">
        {% for some_mission in some_missionlist_pro %}
            <div class="mission-box">
                <a href="{% url 'checklist:mission_modal' some_mission.checklist_id %}">{{ some_mission.checklist.title }}</a>
            </div>
        {% endfor %}
        {% for some_mission in some_missionlist_pre %}
            <div class="mission-box">
                <h3>
                    <a href="{% url 'checklist:mission_modal' some_mission.checklist_id %}">{{ some_mission.checklist.title }}</a>
                </h3>
            </div>
        {% endfor %}
    </div>
</div>

</body>
</html>

checklist/templates/mission_modal.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>misson_modal</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
    <style>
      * {
        font-family: "Apple SD Gothic Neo";
        font-style: normal;
      }
      /* 큰 사이즈 모달창 */
      .modal {
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        display: flex;
        justify-content: center;
        align-items: center;
      }
      .md_overlay {
        background: rgba(0, 0, 0, 0.25);
        width: 100%;
        height: 100%;
        position: absolute;
        display: flex;
        justify-content: center;
        align-items: center;
      }
      .md_content {
        width: 100%;
        height: 420px;
        padding-left: 40px;
        position: fixed;
        bottom: 0;
        background-color: white;
        border-radius: 5px;
      }
      .hidden {
        display: none;
      }
      .md_content > img {
        margin-top: 38px;
        margin-bottom: 20px;
      }
      .md_content > h3 {
        color: #666666;
        font-weight: 800;
        font-size: 25px;
        line-height: 30px;
        margin-top: 0;
        margin-bottom: 14px;
      }
      .md_content > p {
        font-weight: 700;
        font-size: 18px;
        line-height: 22px;
        color: #7a7a7a;
        margin-bottom: 22px;
      }
      .md_content input[type="submit"] {
        margin-bottom: 28px;
        box-sizing: border-box;
        width: 135px;
        height: 45px;
        padding: 10px;
        text-align: center;
        background: #fafafa;
        border: 0.8px solid #c0c0c0;
        border-radius: 5px;
        font-weight: 800;
        font-size: 18px;
        line-height: 22px;
        color: #666666;
        margin-left: 23px;
      }
      .md_content input[type="button"] {
        margin-bottom: 28px;
        box-sizing: border-box;
        width: 135px;
        height: 45px;
        padding: 10px;
        text-align: center;
        background: #fafafa;
        border: 0.8px solid #c0c0c0;
        border-radius: 5px;
        font-size: 18px;
        line-height: 22px;
        font-weight: 800;
        color: #c74e4e;
        margin-right: 23px;
      }
      .md_content input[type="text"] {
        box-sizing: border-box;
        width: 45px;
        font-weight: 800;
        font-size: 65px;
        line-height: 78px;
        color: #666666;
        border: none;
        border-radius: 0px;
      }
      form div {
        display: flex;
        justify-content: center;
        align-items: center;
        margin-right: 50px;
        margin-bottom: 44px;
      }
    </style>
  </head>
  <body>
    <!-- 큰 사이즈 모달창 -->
    <div class="modal hidden">
      <div class="md_overlay">
        <div class="md_content">
          <img
            src="{% static 'blue_star.png' %}"
            alt="별"
            width="25px"
            height="25px"
          />
            {% if member_checklist.checklist.level > 1 %}
          <img
            src="{% static 'blue_star.png' %}"
            alt="별"
            width="25px"
            height="25px"
          />
            {% endif %}
            {% if member_checklist.checklist.level > 3 %}
          <img
            src="{% static 'blue_star.png' %}"
            alt="별"
            width="25px"
            height="25px"
          />
            {% endif %}
          <h3>{{ member_checklist.checklist.title }}</h3>
          <p>
            {{ member_checklist.checklist.content }}
          </p>
          <form action="{% url 'checklist:mission_modal' member_checklist.checklist_id %}" method="post" >

            {% csrf_token %}

              {% if member_checklist.status == -1 %}
              <div>
                  <input type="submit" name="checklist_add" value="추가하기" />
              </div>
              {% else %}
          {% if member_checklist.checklist.is_complete_num == True %}

                  <div>
              <img
                id="button_name"
                value="minus"
                src="{% static 'minus_icon.png' %}"
                alt="마이너스 버튼"
                width="40px"
                height="40px"
                class="minus"

              />
              <input type="text" name="misson_check_value" value="0" readonly />
              <!-- 백엔드로 넘어갈 미션 중간점검 값 -->
                <img
                src="{% static 'sum_icon.png' %}"
                alt="플러스 버튼"
                width="40px"
                height="40px"
                class="plus"
              /><br />
            </div>
              {% endif %}
            <div>
              <input type="submit" name="give_up" value="포기" />
              <input type="submit" name="changeNickModal" value="적용" />
              <input type="submit" name="checklist_complete" value="완료" />
            </div>
              {% endif %}
          </form>
        </div>
      </div>
    </div>
    <script>
      //모달창 열고 닫기 테스트 (bool이 true면 열고 false면 닫음)
      let bool = true;
      if (bool) $(".modal").removeClass("hidden");

      //포기 버튼 누르면 모달창 사라짐
      $("input[name=give_up]").click(() => {
        $(".modal").addClass("hidden");
      });


      //코드가 더럽지만 일단.. 마이너스 이미지 누르면  input의 value값이 3->2->1->0
      $(".minus").click(() => {
        if ($("input[name=misson_check_value]").attr("value") == 3) {
          $("input[name=misson_check_value]").attr("value", "2");
        } else if ($("input[name=misson_check_value]").attr("value") == 2) {
          $("input[name=misson_check_value]").attr("value", "1");
        } else if ($("input[name=misson_check_value]").attr("value") == 1) {
          $("input[name=misson_check_value]").attr("value", "0");
        } else {
          $("input[name=misson_check_value]").attr("value", "0");
        }

      });

      //코드가 더럽지만 일단.. 플러스 이미지 누르면  input의 value값이 0->1->2->3
      $(".plus").click(() => {
        if ($("input[name=misson_check_value]").attr("value") == 0) {
          $("input[name=misson_check_value]").attr("value", "1");
        } else if ($("input[name=misson_check_value]").attr("value") == 1) {
          $("input[name=misson_check_value]").attr("value", "2");
        } else if ($("input[name=misson_check_value]").attr("value") == 2) {
          $("input[name=misson_check_value]").attr("value", "3");
        } else {
          $("input[name=misson_check_value]").attr("value", "3");
        }
      });
    </script>
  </body>
</html>