Mission_Book/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('login.urls')),
    path('checklist',include('checklist.urls')),
]

checklist/urls.py
from django.urls import path
from . import views
from Mission_Book import settings
from django.conf.urls.static import static

app_name = 'checklist'

urlpatterns = [
    path('',views.index_null, name='index_null'),
    path('index/<int:category>',views.index, name='index'),
    path('missionDetail/<int:mission_id>',views.mission_modal, name='mission_modal')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/urls.py
from django.urls import path
from . import views
from Mission_Book import settings
from django.conf.urls.static import static

app_name='login'

urlpatterns = [
    path('join/', views.join, name='join'),
    path('prolog/<int:num>',views.prolog, name='prolog'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.logout_member, name='logout'),
    path('profile/',views.profile, name='profile'),
    path('mypage/',views.mypage, name='mypage'),
    path('setup/',views.setup, name='setup'),
    path('select_title/',views.select_title, name='select_title'),
    path('change_title/<int:title>/',views.change_title, name='change_title'),
    path('change_title_color/<int:color>/',views.change_title_color, name='change_title_color'),
    path('ending/<int:num>',views.ending, name='ending'),
    path('',views.join, name='join')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/models.py
from django.db import models

# Create your models here.

login/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import login, authenticate, logout
from member.models import Member, Title, Graduation
from checklist.models import Checklist,MemberChecklist
from member.forms import MemberCreationForm, LoginForm, ChangeProfileForm, ChangeNameForm
from django.views.generic import View
from django.http import HttpResponse
import pdb
from PIL import Image
import os, io
import datetime


this_year = 2023


def join(request):
    if request.method == 'POST':
        form = MemberCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            checklists = Checklist.objects.all()
            for c in range(len(checklists)):
                print("hi")
                MemberChecklist.objects.create(member=request.user.user_id, checklist=checklists[c], status=-1)        
            return redirect('/prolog/1')
    else:
        form = MemberCreationForm()
    return render(request, 'join.html', {'form': form })




class LoginView(View):
    def get(self, request):
        form = LoginForm()
        return render(request, 'login.html', {'form': form})

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            user_id = form.cleaned_data['user_id']
            password = form.cleaned_data['password']
            user = authenticate(request, user_id=user_id, password=password)
            if user is not None:
                login(request, user)
                return redirect('checklist:index_null')
            else:
                form.add_error('user_id', '로그인 정보가 잘못되었습니다.')
        return render(request, 'login.html', {'form': form})
    

def logout_member(request):
    logout(request)
    return redirect('/login/')


def is_login(request):
    user_id = None
    if request.user.is_authenticated:
        user_id = request.user.user_id  # 혹은 request.user.username 등 로그인한 유저의 정보를 사용

    if not user_id:
        return redirect('checklist:index_null')
    
    if datetime.datetime.now().year!=this_year:
        return redirect('/ending/1')

    return 0
    

def profile(request):
    login = is_login(request)
    if login != 0:
        return login
    
    return render(request, 'profile.html')

def mypage(request):
    login = is_login(request)
    if login != 0:
        return login
    
    titles = Title.objects.all()

    selectable_titles = []
    for title in titles:
        if request.user.can_select_title(title):
            selectable_titles.append(title)
            
    int_num = 0
    social_num = 0
    exp_num = 0
    
    checklists = MemberChecklist.objects.filter(member=request.user.user_id, status = 1)
    for check in checklists:
        if check.checklist.category == 1:
            int_num+=1
        elif check.checklist.category == 2:
            social_num+=1
        else: 
            exp_num+=1


    context = {
        'selectable_titles': selectable_titles,
        'exp_per':str(int((request.user.total_exp%1)*100)),
        'int_num' : int_num,
        'social_num' : social_num,
        'exp_num' : exp_num,
        'total_num' : int_num+social_num+exp_num
    }
    return render(request, 'mypage.html', context)

    
def setup(request):
    login = is_login(request)
    if login != 0:
        return login
    user_id = request.user.user_id
    
    if request.method == 'POST':
        if 'change_profile' in request.POST:
            form = ChangeProfileForm(request.POST, request.FILES)
            if form.is_valid():
                profile_image = form.cleaned_data['profile_image']
                member = Member.objects.get(user_id=user_id)
                img = Image.open(profile_image)
                img = img.convert('RGB')  # RGBA -> RGB 변환
                img = img.resize((100, 100))
                buffer = io.BytesIO()
                img.save(buffer, "JPEG")
                member.profile_image.save(profile_image.name, buffer, save=True)
                return redirect('mypage')
        elif 'change_name' in request.POST:
            form = ChangeNameForm(request.POST)
            if form.is_valid():
                new_name = form.cleaned_data['name']
                member = Member.objects.get(user_id=user_id)
                if new_name != member.name: # 변경된 이름이 있는 경우에만 업데이트
                    member.name = new_name
                    member.save()
                return redirect('mypage')
        elif 'unregister' in request.POST:
            user_id = request.user.user_id
            member = Member.objects.get(user_id=user_id)
            member.is_active = False
            member.save()
            return redirect('checklist:index_null')

    form1 = ChangeProfileForm()
    form2 = ChangeNameForm()
    return render(request, 'setup.html', {'form1': form1, 'form2': form2 })



def select_title(request):
    login = is_login(request)
    if login != 0:
        return login
    
    titles = Title.objects.all()

    # Divide titles into selectable and non-selectable
    selectable_titles = []
    non_selectable_titles = []
    for title in titles:
        if request.user.can_select_title(title):
            selectable_titles.append(title)
        else:
            non_selectable_titles.append(title)

    context = {
        'selectable_titles': selectable_titles,
        'non_selectable_titles': non_selectable_titles,
    }
    return redirect('login:mypage')


def change_title(request, title):
    login = is_login(request)
    if login != 0:
        return login
    
    user_id = request.user.user_id
    
    title = Title.objects.get(id=title)
    if request.user.can_select_title(title):
        member = Member.objects.get(user_id=user_id)
        member.title = title
        member.save()
    return redirect('login:select_title')


def change_title_color(request, color):
    login = is_login(request)
    if login != 0:
        return login

    user_id = request.user.user_id
    
    if 0<=color<6:
        member = Member.objects.get(user_id=user_id)
        member.title_color = color
        member.save()
    return redirect(select_title)


def ending(request, num):
    user_id = None
    if request.user.is_authenticated:
        user_id = request.user.user_id

    if not user_id and datetime.datetime.now().year==this_year:
        return redirect('checklist:index_null')

    if num == 1:
        return render(request, "ending.html")
    elif num == 2:
        return render(request, "ending2.html")
    elif num == 3:
        int_num = 0
        social_num = 0
        exp_num = 0
        
        checklists = MemberChecklist.objects.filter(member=request.user.user_id, status = 1)
        for check in checklists:
            if check.checklist.category == 1:
                int_num+=1
            elif check.checklist.category == 2:
                social_num+=1
            else: 
                exp_num+=1
        total_num = int_num+social_num+exp_num
        graduation = Graduation.objects.all().order_by('-order')
        for g in graduation:
            if request.user.can_graduation(g):
                return render(request, "ending3.html", {"graduation": g, "int_num":int_num,"social_num":social_num,"exp_num":exp_num,"total_num":total_num})
        


def prolog(request,num):
    user_id = None
    if request.user.is_authenticated:
        user_id = request.user.user_id

    if not user_id and datetime.datetime.now().year!=this_year:
        return redirect('checklist:index_null')

    if num == 1:
        return render(request, "prolog.html")
    elif num == 2:
        return render(request, "prolog2.html")

login/templates/ending.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ending</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.11.4/gsap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
    <style>
        *{
            font-family: 'Apple SD Gothic Neo';
            font-style: normal;
            font-weight: 700;
            font-size: 19px;
            line-height: 24px;
            text-align: center;
            color: #8C8C8C;
        }
        .visual{
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }
        p:first-of-type{
            margin-top: 148px;
        }
        p:last-of-type{
            margin-bottom: 92px;
        }
        p{
            margin-bottom: 40px;
        }
        .nick{
            color:#666666;
        }

        .visual div{
            margin-bottom: 184px;
            width: 200px;
            height: 120px;
            background: #D9D9D9;
        }
        .fade_in{
            opacity: 0;
        }
    </style>
</head>
<body>
    <div class="visual">
        <p class="fade_in"><span class="nick">{{user.name}}</span>님, 고생하셨습니다<br/>
            어느새 시간이 흘러<br/>
            새내기 졸업을 앞두고 있습니다.
        </p>
        <p class="fade_in">당신의 새내기는 어땠나요? <br/> 결과가 어떻든간에 <br/> 
            당신의 새내기는<br/> 세상에 단 하나 뿐인 추억입니다.</p>
        <p class="fade_in">앞으로의 대학생활과 이후의 행보를<br/> 진심으로 응원합니다!</p>
        <div class="fade_in"></div>
    </div>
    <script>

        // 시간차 문단 보이기
        const fadeEls = document.querySelectorAll('.fade_in');
        fadeEls.forEach((fadeEl, index)=>{
            gsap.to(fadeEl, 3, {
            delay : (index + 1) * .9,
            opacity:1
        })
        });

        // 바디 클릭시 프롤로그 다음 페이지로 넘어감
        $('body').click(()=>{ window.location.href = "{% url 'ending' num=2 %}"; });
    </script>
</body>
</html>

login/templates/ending2.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ending2</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.11.4/gsap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
    <style>
      .visual {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
      }
      img {
        margin-top: 310px;
      }
      p {
        margin-top: 20px;
        margin-bottom: 295px;
        font-family: "Apple SD Gothic Neo";
        font-style: normal;
        font-weight: 700;
        font-size: 17px;
        line-height: 20px;
        text-align: center;
        color: #8c8c8c;
      }
      .fade_in {
        opacity: 0;
      }
    </style>
  </head>
  <body>
    <div class="visual">
      {% load static %}
      <img
        src="{% static 'team_logo.png' %}"
        width="250px"
        height="225px"
        alt="팀로고"
        class="fade_in"
      />
      <p class="fade_in">made by. 멋쟁이 사자처럼 벚꽃톤 9팀</p>
    </div>
    <script>
      // 시간차 문단 보이기
      const fadeEls = document.querySelectorAll(".fade_in");
      fadeEls.forEach((fadeEl, index) => {
        gsap.to(fadeEl, 2, {
          delay: (index + 1) * 0.9,
          opacity: 1,
        });
      });

      // 바디 클릭시 미션 화면으로 넘어감
      $("body").click(() => {
        window.location.href = "{% url 'ending' num=3 %}";
      });
    </script>
  </body>
</html>

login/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>login</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
    <style>
        *{
            font-family: 'Apple SD Gothic Neo';
            font-style: normal;
            font-weight: 700;
            font-size: 20px;
            line-height: 24px;
        }
        body{
            display: flex;
            justify-content: center;
            align-items: center;
            flex-direction: column;
            margin: 0;
        }
        #homeLogo{
            margin-top: 166px;
            width: 68px;
            height: 68px;
            background: #F5F5F5;
            border: 0.5px solid #C0C0C0;
            border-radius: 35px;
        }
        h1{
            margin-top: 35px;
            margin-bottom: 5px;
            font-family: 'Apple SD Gothic Neo';
            font-style: normal;
            font-weight: 900;
            font-size: 28px;
            line-height: 34px;
        }
        p{
            margin-top: 0;
            margin-bottom: 122px;
            font-style: normal;
            font-weight: 700;
            font-size: 18px;
            line-height: 22px;
            color: #666666;
        }
        input{
            box-sizing: border-box;
            width: 300px;
            height: 60px;
            background: #FDFDFD;
            border: 0.8px solid #C0C0C0;
            border-radius: 10px;
            margin-bottom: 12px;
            padding: 18px;
        }
        input::placeholder{
            color: #A7A7A7;
        }
        input[type="submit"]{
            background: #F2F2F2;
            margin-top: 48px;
            margin-bottom: 12px;
            color: #666666;
        }
        a{
            color: #666666;
            text-decoration: none;
            margin-bottom: 148px;
            font-size: 15px;
            line-height: 18px;
        }
        
        /* 모달창 css */
        .modal{
            position: fixed;
            top: 0; left: 0;
            width: 100%; height: 100%;
            display: flex;
            justify-content: center;
            align-items: center;
        }
        .md_overlay{
            background: rgba(0, 0, 0, 0.25);
            width: 100%; height: 100%;
            position: absolute;
            display: flex;
            justify-content: center;
            align-items: center;
        }
        .md_content{
            width: 300px; height: 230px;
            position: relative;
            background-color: white;
            text-align: center;
            border-radius: 5px;
        }
        .hidden{
            display: none;
        }
        .md_content>h3{
            color: #666666;
            font-weight: 800;
            font-size: 25px;
            line-height: 30px;
            margin-top: 42px;
            margin-bottom: 14px;
        }
        .md_content>p{
            font-weight: 700;
            font-size: 18px;
            line-height: 22px;
            color: #7A7A7A;
            margin-bottom: 49px;
        }
        .md_content>input{
            margin-bottom: 28px;
            box-sizing: border-box;
            width: 150px; height: 45px;
            padding: 10px;
        }
    </style>
</head>
<body>
    <div id="homeLogo"></div>
    <h1>MISSION BOOK</h1>
    <p>새내기를 위한🌱</p>
    <form method="post">
        {% csrf_token %}
        {{ form.user_id }}<br />
        {{ form.password }}<br />
    <input type="submit" name="login" value="로그인" />
    </form>
    <a href="{% url 'login:join' %}">회원가입</a>

    {% if form.user_id.errors %}
    <!-- 모달창 -->
    <div class="modal">
        <div class="md_overlay">
            <div class="md_content">
                <h3>로그인 오류</h3>
                <p>{{form.user_id.errors.0}}</p>
                <input type="button" name="loginErrorModal" value="확인"/>
            </div>
        </div>
    </div>
    <script>
        // 모달창의 확인 버튼 누를시 모달창 없어짐
        $('input[name=loginErrorModal]').click(()=>{location.href = "{% url 'login:login' %}";});
        // 로그인 입력 오류시 모달창 보임
        $('input[name=login]').click(()=>{$('.modal').removeClass('hidden')});
    </script>
    {% endif %}
</body>
</html>

login/templates/mypage.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="{% static 'style.css' %}" />

    <title>📚MissionBook - MyPage</title>
  </head>

  <body>
    <header>
      <a href="{% url 'checklist:index_null' %}"><img src="{% static 'misson.png' %}" alt="미션아이콘" width="25px" height="25px"/></a>
      <a href="{% url 'login:mypage' %}"><img src="{% static 'info_click.png' %}" alt="정보아이콘" width="25px" height="25px"/></a>
      <a href="{% url 'login:setup' %}"><img src="{% static 'setup.png' %}" alt="설정아이콘" width="25px" height="25px"/></a>
  </header>
    <!-- 사용자 정보 -->
    <div id="userTab">
      <img id="userImg" src="/media/{{ user.profile_image }}" alt="사용자 이미지" />
      <p>
        <span id="username">{{user.name}}</span>&nbsp;<span id="level">LV.{{ user.total_exp|add:0 }}</span
        ><br /><span id="title">{% if user.title %}{{user.title}}{% else %} 칭호없음 {% endif %}</span>
      </p>
    </div>
    <hr />
    <!-- 메뉴 -->
    <div class="tab_menu">
      <ul class="list">
        <!-- 스탯 -->
        <li class="is_on">
          <a href="#stats" class="btn">스탯</a>
          <div id="stats" class="cont">
            <p class="menu-title">🚩 현재 레벨</p>
            <div class="menu-detail">
              <p>LV. {{ user.total_exp|add:0 }}</p>
              <p class="per">
                <!-- max 100%, value 값에 따라 설정 -->
                <progress id="progress" value="{{exp_per}}" max="100"></progress>
              <p id="per_value"> {{exp_per}}% </p>
              </p>
            </div>
            <br />
    
            <p class="menu-title">💪🏻 현재 스탯</p>
            <div class="menu-detail">
              <p>학업&nbsp;&nbsp;<span id="study">{{user.int_stat|add:0}}</span></p>
              <p>사교&nbsp;&nbsp;<span id="social">{{user.social_stat|add:0}}</span></p>
              <p>경험&nbsp;&nbsp;<span id="exp">{{user.exp_stat|add:0}}</span></p>
            </div>
            <br />
    
            <p class="menu-title">📜 지금까지 완료한 미션</p>
            <div class="menu-detail">
              <p>학업&nbsp;&nbsp;<span id="study-complete">{{int_num}}</span>개</p>
              <p>사교&nbsp;&nbsp;<span id="social-complete">{{social_num}}</span>개</p>
              <p>경험&nbsp;&nbsp;<span id="exp-complete">{{exp_num}}</span>개</p>
              <p>총&nbsp;&nbsp;<span id="total">{{total_num}}</span>개</p>
          </div>
        </li>
        <!-- 칭호 -->
        <li>
          <a href="#title" class="btn">칭호</a>
          <div id="title" class="cont">
            <div id="box" class="box">
              <div id="palletBox" class="pallet">
              </div>
              <button id="apply" type="button">적용</button>
          </div>
          <br/>
          <div class="title-wrap">
            {% for title in selectable_titles %}
            <p class="title-text"><a href="{% url 'login:change_title' title.id %}?title_id={{ title.id }}">{{ title }}</a></p>
            {% endfor %}
        </div>
          </div>
        </li>
        <!-- 완료 -->
        <li>
          <a href="#complete" class="btn">완료</a>
          <div id="complete" class="cont">
            <ul>
              <li class="is_sub">
                <a href="#sub-complete-study" class="sub-btn">📖</a>
                <div id="sub-complete-study" class="sub-cont">
                  <div class="sub-wrap-study">
                    <span id="star-study">★</span>
                    <p id="text-study">토익 200점 넘기</p>
                  </div>
                  <div class="sub-wrap-study">
                    <span id="star-study">★</span>
                    <p id="text-study">토익 200점 넘기</p>
                  </div>
                  <div class="sub-wrap-study">
                    <span id="star-study">★</span>
                    <p id="text-study">토익 200점 넘기</p>
                  </div>
                  <div class="sub-wrap-study">
                    <span id="star-study">★</span>
                    <p id="text-study">토익 200점 넘기</p>
                  </div>
                  <div class="sub-wrap-study">
                    <span id="star-study">★</span>
                    <p id="text-study">토익 200점 넘기</p>
                  </div>
              </div>
            </li>
            <li>
              <a href="#sub-complete-social" class="sub-btn">🌼</a>
              <div id="sub-complete-social" class="sub-cont">
                <div class="sub-wrap-social">
                  <p id="star-social">★</p>
                  <p id="text-social">토익 200점 넘기</p>
                </div>
                <div class="sub-wrap-social">
                  <p id="star-social">★</p>
                  <p id="text-social">토익 200점 넘기</p>
                </div>
                <div class="sub-wrap-social">
                  <p id="star-social">★</p>
                  <p id="text-social">토익 200점 넘기</p>
                </div>
                <div class="sub-wrap-social">
                  <p id="star-social">★</p>
                  <p id="text-social">토익 200점 넘기</p>
                </div>
                <div class="sub-wrap-social">
                  <p id="star-social">★</p>
                  <p id="text-social">토익 200점 넘기</p>
                  <div class="sub-wrap-social">
                    <p id="star-social">★</p>
                    <p id="text-social">토익 200점 넘기</p>
                  </div>
                </div>
            </div>
          </li>
          <li >
            <a href="#sub-complete-exp" class="sub-btn">🧭</a>
            <div id="sub-complete-exp" class="sub-cont">
              <div class="sub-wrap-exp">
                <p id="star-exp">★</p>
                <p id="text-exp">토익 200점 넘기</p>
              </div>
              <div class="sub-wrap-exp">
                <p id="star-exp">★</p>
                <p id="text-exp">토익 200점 넘기</p>
              </div>
              <div class="sub-wrap-exp">
                <p id="star-exp">★</p>
                <p id="text-exp">토익 200점 넘기</p>
              </div>
              <div class="sub-wrap-exp">
                <p id="star-exp">★</p>
                <p id="text-exp">토익 200점 넘기</p>
              </div>
              <div class="sub-wrap-exp">
                <p id="star-exp">★</p>
                <p id="text-exp">토익 200점 넘기</p>
              </div>
              <div class="sub-wrap-exp">
                <p id="star-exp">★</p>
                <p id="text-exp">토익 200점 넘기</p>
              </div>
          </div>
        </li>
          </ul>
        </div>
        </li>
      </ul>
    </div>
    <script src="{% static 'mypage.js' %}"></script>
  </body>
</html>

login/templates/prolog.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Prolog</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.11.4/gsap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
    <style>
        *{
            font-family: 'Apple SD Gothic Neo';
            font-style: normal;
            font-weight: 700;
            font-size: 19px;
            line-height: 24px;
            text-align: center;
            color: #8C8C8C;
        }
        body{
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }
        p:first-of-type{
            margin-top: 148px;
        }
        p:last-of-type{
            margin-bottom: 191px;
        }
        p{
            margin-bottom: 40px;
        }
        .nick, .strong{
            color:#666666;
        }
        .red{
            color: #C74E4E;
        }

        .fade_in{
            opacity: 0;
        }
    </style>
</head>
<body>
    <div class="visual">
        <p class="fade_in"><span class="nick">{{user.name}}</span>님, 안녕하세요?<br/>
            지금부터 <span class="nick">{{user.name}}</span>님의 <br/>
            행복한 새내기 생활을 위해<br/> 
            맞춤 미션 제공 서비스를 시작합니다! 
        </p>
        <p class="fade_in">저희가 제공하는 미션을 통해 <br/> 즐거운 새내기 생활을 보내시기 바랍니다.</p>
        <p class="fade_in">저희 서비스는 <span class="red">실제 행동</span>에 따라<br/> 결과값을 입력해야<br/> 가장 효과가 좋다는 점을 명심해주세요.</p>
        <p class="fade_in">마지막으로, 저희는 서비스 취지상<br/> 새내기 기간인<br/> 현재 날짜부터 올해 <span class="strong">12월 31일</span>까지만<br/>서비스를 
            이용하실 수 있습니다.
        </p>
        <p class="fade_in">그러면, 즐거운 새내기 생활되세요 🙂</p>
    </div>

    <script>

        // 시간차 문단 보이기
        const fadeEls = document.querySelectorAll('.fade_in');
        fadeEls.forEach((fadeEl, index)=>{
            gsap.to(fadeEl, 2, {
            delay : (index + 1) * .9,
            opacity:1
        })
        });

        // 바디 클릭시 프롤로그 다음 페이지로 넘어감
        $('body').click(()=>{ window.location.href = "{% url 'login:prolog' num=2 %}"; });

    </script>
</body>
</html>

login/templates/prolog2.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>prolog2</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.11.4/gsap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
    <style>
      .visual {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
      }
      .visual div {
        margin-top: 228px;
        margin-bottom: 28px;
        width: 200px;
        height: 120px;
        background: #d9d9d9;
      }
      p {
        margin-top: 20px;
        font-family: "Apple SD Gothic Neo";
        font-style: normal;
        font-weight: 700;
        font-size: 17px;
        line-height: 20px;
        text-align: center;
        color: #8c8c8c;
      }
      .fade_in {
        opacity: 0;
      }
    </style>
  </head>
  <body>
    <div class="visual">
      <div class="fade_in"></div>
      <img
        src="{% static 'team_logo.png' %}"
        width="250px"
        height="225px"
        alt="팀로고"
        class="fade_in"
      />
      <p class="fade_in">made by. 멋쟁이 사자처럼 벚꽃톤 9팀</p>
    </div>
    <script>
      // 시간차 문단 보이기
      const fadeEls = document.querySelectorAll(".fade_in");
      fadeEls.forEach((fadeEl, index) => {
        gsap.to(fadeEl, 2, {
          delay: (index + 1) * 0.9,
          opacity: 1,
        });
      });

      // 바디 클릭시 미션 화면으로 넘어감
      $("body").click(() => {
        window.location.href = "{% url 'checklist:index_null' %}";
      });
    </script>
  </body>
</html>